const PAGES = {
home:{title:'Command Center',sub:'Central hub for BCSO policies, operations, divisions, and reference material.',category:'HOME'},
'quick-reaction':{title:'Quick Reaction Handbook',category:'OPERATIONS',sub:'Immediate-response framework for priority incidents.',draft:true,blocks:[['Priority Response','Define calls eligible for priority response, required notifications, supervisor involvement, and response limitations.'],['Scene Arrival','Define arrival responsibilities, scene security, command designation, and radio updates.'],['Critical Incidents','Define procedures for active threats, officer-down events, barricades, major crashes, and other high-risk incidents.'],['After Action','Define required reports, evidence preservation, supervisor review, and post-incident requirements.']]},
patrol:{title:'Patrol Operations',category:'OPERATIONS',sub:'Routine patrol expectations and field procedures.',draft:true,blocks:[['Patrol Status','Define available, unavailable, traffic, scene, transport, and other status rules.'],['Vehicle Checks','Define required vehicle and equipment checks before patrol.'],['Routine Stops','Define approach, identification, communication, records checks, and release procedures.'],['Supervisor Contact','Define when a supervisor must be notified or requested.']]},
communications:{title:'Communications & Radio',category:'OPERATIONS',sub:'Radio discipline, dispatch coordination, and communications standards.',draft:true,blocks:[['Radio Discipline','Keep transmissions concise, professional, and relevant. Replace this framework with the approved standard.'],['Priority Traffic','Define emergency traffic wording, channel restrictions, and dispatch priority procedures.'],['Identifiers','Define callsigns, unit numbers, department identifiers, and supervisor designations.'],['Dispatch Requests','Define BOLOs, tow requests, EMS requests, backup, records checks, and scene notifications.']]},
traffic:{title:'Traffic & Pursuits',category:'OPERATIONS',sub:'Traffic stops, pursuits, emergency driving, and intervention references.',draft:true,blocks:[['Traffic Stops','Define stop initiation, positioning, communication, records checks, and release/arrest workflow.'],['Vehicle Pursuits','Define initiation factors, supervisor oversight, radio updates, termination criteria, and reporting.'],['PIT / Intervention','Define authorized intervention methods, conditions, restrictions, and required documentation.'],['Emergency Driving','Define lights/siren use, intersections, speed expectations, and officer-safety requirements.']]},
arrest:{title:'Arrest & Booking',category:'OPERATIONS',sub:'Arrest processing, transport, booking, and release references.',draft:true,blocks:[['Arrest','Define probable cause, arrest procedures, rights advisement, searches, and documentation.'],['Transport','Define prisoner search, restraints, vehicle placement, destination, and transfer procedures.'],['Booking','Define property, charges, evidence, records, screenshots/forms, and release/transfer workflow.'],['Supervisor Review','Define cases requiring supervisor approval or additional documentation.']]},
impounding:{title:'Impounding',category:'OPERATIONS',sub:'Vehicle impound, tow, evidence, and release references.',draft:true,blocks:[['Impound Criteria','Define the circumstances under which a vehicle may be towed or impounded.'],['Inventory / Evidence','Define inventory requirements, evidence handling, photographs, and documentation.'],['Tow Requests','Define dispatch/tow procedures and required vehicle information.'],['Release','Define authorized release, fees, records, and documentation.']]},
conduct:{title:'Code of Conduct',category:'POLICY',sub:'Professional standards and member expectations.',draft:true,blocks:[['Professionalism','Define expected conduct toward civilians, fellow members, supervisors, and partner agencies.'],['Integrity','Define honesty, reporting obligations, evidence integrity, and conflicts of interest.'],['Department Resources','Define appropriate use of vehicles, equipment, communications, records, and internal systems.'],['Social Media / OOC','Define separation of roleplay and out-of-character conduct where applicable.']]},
force:{title:'Use of Force & Firearms',category:'POLICY',sub:'Use-of-force principles, reporting, and firearms references.',draft:true,blocks:[['Force Principles','Define authorized force, necessity, proportionality, de-escalation, and duty-to-act requirements.'],['Firearms','Define carry, display, discharge, storage, and authorization requirements.'],['Reporting','Define when force, firearm display, discharge, injury, or other critical events require reports.'],['Supervisor Review','Define mandatory supervisor response and administrative review thresholds.']]},
uniform:{title:'Uniform & Equipment',category:'POLICY',sub:'Uniform standards, issued equipment, and approved loadouts.',draft:true,table:[['Category','Reference'],['Patrol Uniform','Define shirt, pants, boots, vest, duty belt, and identifiers.'],['Supervisor Uniform','Define rank markings and supervisor-specific equipment.'],['Specialty Uniforms','Define CID, SWAT, TEU / HEAT, Air-1, and other specialty attire.'],['Equipment','Define approved equipment and any rank/unit restrictions.']]},
discipline:{title:'Discipline & Infractions',category:'POLICY',sub:'Internal accountability and administrative reference.',draft:true,blocks:[['Minor Infractions','Define coaching, documentation, retraining, and other responses.'],['Major Infractions','Define investigation, suspension, demotion, removal, or other authorized outcomes.'],['Reporting','Define complaint intake, evidence standards, confidentiality, and review.'],['Appeals','Define who may appeal and the approved process/timeline.']]},
activity:{title:'Activity & Leave',category:'POLICY',sub:'Activity expectations, LOA, inactivity, and return-to-duty references.',draft:true,blocks:[['Activity','Define minimum activity expectations and how activity is recorded.'],['Leave of Absence','Define LOA request process, maximum duration, extensions, and return procedures.'],['Inactivity','Define inactivity notifications, administrative review, and reinstatement requirements.'],['Return to Duty','Define retraining or supervisor review required after extended leave.']]},
'off-duty':{title:'Off-Duty Guidelines',category:'POLICY',sub:'Off-duty expectations and roleplay boundaries.',draft:true,blocks:[['Conduct','Define conduct that may affect department standing while off duty.'],['Equipment','Define when department equipment or vehicles may be used off duty.'],['Roleplay Separation','Define OOC disputes, Discord conduct, and roleplay boundaries.'],['Outside Agencies','Define interactions with other departments and conflicts of authority.']]},
structure:{title:'Department Structure',category:'DEPARTMENT',sub:'Command structure and organizational reference.',draft:true,org:[['Executive','BCSO Command'],['Operations','Patrol Division'],['Investigations','CID'],['Special Operations','SWAT / TEU / HEAT'],['Aviation','Air-1']]},
certifications:{title:'Special Certifications',category:'DEPARTMENT',sub:'Special certifications and qualification tracking.',draft:true,blocks:[['Field Training','FTO qualification and evaluation framework.'],['TEU / HEAT','Traffic-enforcement specialty qualification.'],['Air-1','Aviation qualification and flight standards.'],['SWAT','Special weapons qualification framework.']]},
vehicles:{title:'Police Vehicles',category:'DEPARTMENT',sub:'Fleet, vehicle assignments, and approved configurations.',draft:true,table:[['Assignment','Vehicle Reference','Status'],['Patrol','Approved patrol fleet','DRAFT'],['Supervisor','Supervisor fleet','DRAFT'],['CID','Unmarked / investigative fleet','DRAFT'],['Special Operations','SWAT / TEU / Air-1 support','DRAFT']]},
training:{title:'Academy & FTO',category:'DEPARTMENT',sub:'Recruit training, field training, and evaluation references.',draft:true,timeline:[['01','Academy','Define classroom curriculum, practical exercises, testing, and graduation requirements.'],['02','FTO Phase','Define field-training phases, daily evaluations, remediation, and sign-off requirements.'],['03','Probation','Define probationary period, performance expectations, and final review.'],['04','Certification','Define specialty qualification pathways after basic field certification.']]},
cid:{title:'Criminal Investigation Division',category:'DEPARTMENT',sub:'CID organization, case handling, and investigative references.',draft:true,blocks:[['Case Intake','Define case assignment, priority, documentation, and supervisor oversight.'],['Investigations','Define interviews, evidence, surveillance, records, warrants, and interagency coordination.'],['Case Files','Define required documentation and retention.'],['Arrests','Define investigative arrest coordination and required notifications.']]},
swat:{title:'SWAT',category:'DEPARTMENT',sub:'Special Weapons and Tactics division reference.',draft:true,blocks:[['Activation','Define qualifying incidents and who may activate the unit.'],['Command','Define tactical command and incident-command relationships.'],['Equipment','Define approved specialty equipment and qualification requirements.'],['After Action','Define documentation, debrief, and review.']]},
teu:{title:'TEU / HEAT',category:'DEPARTMENT',sub:'Traffic Enforcement Unit / Highway Enforcement & Apprehension Team.',draft:true,blocks:[['Mission','Define the unit mission and patrol area.'],['Qualifications','Define selection, training, pursuit, motorcycle, and intervention qualifications.'],['Equipment','Define approved vehicles, equipment, and specialty tools.'],['Reporting','Define enforcement statistics, pursuit reporting, and supervisor review.']]},
air1:{title:'Air-1',category:'DEPARTMENT',sub:'BCSO aviation / helicopter division reference.',draft:true,blocks:[['Mission','Define patrol, pursuit support, search, rescue, and scene-support missions.'],['Pilot Qualifications','Define training, currency, check rides, and authorization.'],['Flight Operations','Define takeoff, landing, communications, airspace, emergency, and weather procedures.'],['Coordination','Define ground-unit requests, tactical support, and incident-command coordination.']]},
commands:{title:'Common Commands',category:'RESOURCES',sub:'Quick-access command reference for BCSO members.',draft:true,commands:[['/duty','Duty toggle'],['/me','Roleplay action'],['/911','Emergency / dispatch request'],['/mdt','MDT access']]},
radio:{title:'Radio / 10-Codes',category:'RESOURCES',sub:'Radio shorthand and communications reference.',draft:true,table:[['Code','Meaning','Status'],['10-4','Acknowledged / understood','VERIFY'],['10-8','In service / available','VERIFY'],['10-7','Out of service','VERIFY'],['10-20','Location','VERIFY'],['10-80','Vehicle pursuit','VERIFY']]},
'penal-code':{title:'Penal Code',category:'RESOURCES',sub:'Legal reference framework for server-specific charges.',banner:'REPLACE WITH SERVER PENAL CODE',blocks:[['Criminal Offenses','Insert approved Red Willow RP criminal-offense categories and charge IDs.'],['Traffic Offenses','Insert approved traffic violations, fines, and license consequences.'],['Weapons','Insert approved weapons offenses and authorization rules.'],['Sentencing / Fines','Insert the current server-approved fine and sentencing schedule.']]},
documents:{title:'Forms & Documents',category:'RESOURCES',sub:'Central location for department forms and shared resources.',draft:true,links:[['Incident Report','Add your approved report form or document.'],['Arrest Report','Add your approved arrest/booking form.'],['Pursuit Report','Add your approved pursuit review form.'],['LOA Request','Add your approved leave request form.']]},
announcements:{title:'Announcements',category:'RESOURCES',sub:'Department updates and command notices.',draft:true,announcements:[['INITIAL RELEASE','The Red Willow BCSO policy portal is ready for approved policy, training, and command material.'],['VERIFY YOUR REVISION','Always use the current policy revision displayed by command before relying on a procedure.']]}
};

const nav = [...document.querySelectorAll('#sidebar a[data-route]')];
const main = document.querySelector('#main');

function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function renderHome(){
  return `<section class="hero"><div class="hero-inner"><div class="hero-copy"><div class="kicker">RED WILLOW ROLE PLAY • BLAINE COUNTY</div><h1>BLAINE COUNTY<br><em>SHERIFF'S OFFICE</em></h1><div class="hero-rule"></div><p>STANDARD OPERATING PROCEDURES</p><small>SERVICE • INTEGRITY • COMMUNITY • PROFESSIONALISM</small></div><img class="hero-patch" src="assets/bcso-patch.webp" alt=""><div class="hero-stamp">BCSO<br><b>COMMAND</b><br>PORTAL</div></div></section>
  <section class="content"><div class="statusbar"><div><span>PORTAL STATUS</span><b class="live">● OPERATIONAL</b></div><div><span>REVISION</span><b>V3</b></div><div><span>CONTENT STATE</span><b>DRAFT / VERIFY</b></div><div><span>JURISDICTION</span><b>BLAINE COUNTY</b></div></div>
  <div class="welcome"><div class="panel"><div class="eyebrow">WELCOME</div><h2>One portal for the whole department.</h2><p>Use the left navigation to move between operations, policy, divisions, training, and reference material. The site is built as a static GitHub Pages app so the same design can later move to a custom domain.</p><div class="callout"><strong>Important</strong><span>Policy placeholders are intentional. Replace them with your approved Red Willow BCSO rules before publishing them as official policy.</span></div></div><div class="panel"><div class="eyebrow">FIELD READY</div><h2>Fast access</h2><p>Jump straight to the references officers are likely to use during a shift.</p><a class="quick" href="#commands"><b>⌘</b><span>Common Commands</span><small>Server commands</small></a></div></div>
  <div class="section-head"><div><div class="eyebrow">OPERATIONS</div><h2>Quick Access</h2></div></div><div class="quick-grid"><a class="quick" href="#quick-reaction"><b>⚡</b><span>Quick Reaction</span><small>Immediate response</small></a><a class="quick" href="#patrol"><b>✦</b><span>Patrol Operations</span><small>Routine patrol</small></a><a class="quick" href="#communications"><b>◉</b><span>Communications</span><small>Radio & dispatch</small></a><a class="quick" href="#traffic"><b>▣</b><span>Traffic & Pursuits</span><small>Stops & pursuits</small></a><a class="quick" href="#force"><b>⬟</b><span>Use of Force</span><small>Force & firearms</small></a></div>
  <div class="section-head"><div><div class="eyebrow">SPECIALIZED UNITS</div><h2>Department Divisions</h2></div></div><div class="division-grid"><a href="#cid" class="division"><span class="division-icon">⌕</span><div><b>CRIMINAL INVESTIGATIONS DIVISION</b><small>CID • CASES • EVIDENCE • WARRANTS</small></div><span>→</span></a><a href="#swat" class="division"><span class="division-icon">✚</span><div><b>SPECIAL WEAPONS & TACTICS</b><small>SWAT • HIGH-RISK OPERATIONS</small></div><span>→</span></a><a href="#teu" class="division"><span class="division-icon">◇</span><div><b>TRAFFIC ENFORCEMENT UNIT / HEAT</b><small>TRAFFIC • ENFORCEMENT • HIGHWAY</small></div><span>→</span></a><a href="#air1" class="division"><span class="division-icon">✈</span><div><b>AIR-1</b><small>AVIATION • OVERWATCH • SEARCH</small></div><span>→</span></a></div>
  <div class="two-col"><div class="panel announce"><div class="panel-title">⚑ DEPARTMENT ANNOUNCEMENTS</div><article><time>INITIAL RELEASE</time><h3>BCSO SOP PORTAL</h3><p>Command-approved policies can be published here as they are finalized.</p></article><article><time>POLICY</time><h3>VERIFY YOUR SOP REVISION</h3><p>Always use the current approved revision before relying on a procedure.</p></article></div><div class="panel"><div class="panel-title">▤ DOCUMENT STATUS</div><div class="doc-status"><span>ACTIVE</span><b>Published SOPs</b><small>Approved policy content</small></div><div class="doc-status draft"><span>DRAFT</span><b>Pending Command Review</b><small>Not active until approved</small></div><div class="doc-status ref"><span>REFERENCE</span><b>Training Materials</b><small>Supporting material</small></div></div></div></section>`;
}
function renderPage(key,p){
  const banner=p.banner || (p.draft?'DRAFT / VERIFY':'');
  let body='';
  if(p.blocks) body+=`<div class="grid2">${p.blocks.map(x=>`<section class="policy"><h2>${esc(x[0])}</h2><p>${esc(x[1])}</p></section>`).join('')}</div>`;
  if(p.table) body+=`<div class="table-wrap"><table><thead><tr>${p.table[0].map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${p.table.slice(1).map(r=>`<tr>${r.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
  if(p.commands) body+=`<div class="command-grid">${p.commands.map(x=>`<div class="command"><code>${esc(x[0])}</code><span>${esc(x[1])}</span><button data-copy="${esc(x[0])}">Copy</button></div>`).join('')}</div>`;
  if(p.org) body+=`<div class="org">${p.org.map((x,i)=>`<div class="org-box"><small>${esc(x[0])}</small><strong>${esc(x[1])}</strong>${i===0?'<p>Replace this organizational framework with the current approved command chart.</p>':''}</div>`).join('')}</div>`;
  if(p.timeline) body+=`<div class="timeline">${p.timeline.map(x=>`<div class="timeline-row"><div class="timeline-num">${esc(x[0])}</div><div class="timeline-body"><h3>${esc(x[1])}</h3><p>${esc(x[2])}</p></div></div>`).join('')}</div>`;
  if(p.links) body+=`<div class="grid2">${p.links.map((x,i)=>`<a class="policy" href="#" onclick="return false"><div class="eyebrow">RESOURCE ${String(i+1).padStart(2,'0')}</div><h2>${esc(x[0])}</h2><p>${esc(x[1])}</p><span class="card-link">ADD LINK →</span></a>`).join('')}</div>`;
  if(p.announcements) body+=p.announcements.map(x=>`<section class="policy" style="margin-bottom:12px"><div class="eyebrow">${esc(x[0])}</div><p>${esc(x[1])}</p></section>`).join('');
  return `<section class="page"><div class="crumb"><a href="#home">Command Center</a> <span>/</span> ${esc(p.title)}</div><header class="page-head"><div class="eyebrow">${esc(p.category)}</div><h1>${esc(p.title)}</h1><p>${esc(p.sub)}</p></header>${banner?`<div class="draft-banner"><b>${esc(banner)}</b><span>${p.banner?'This page intentionally contains no fabricated statute numbers or sentencing values.':'This is a framework page. Replace the placeholders with approved Red Willow BCSO material before treating it as authoritative.'}</span></div>`:''}${body}</section>`;
}
function route(){
  const key=location.hash.replace('#','') || 'home';
  const p=PAGES[key] || PAGES.home;
  main.innerHTML=key==='home'?renderHome():renderPage(key,p);
  nav.forEach(a=>a.classList.toggle('active',a.dataset.route===key));
  window.scrollTo(0,0);
  document.querySelectorAll('[data-copy]').forEach(btn=>btn.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(btn.dataset.copy);const old=btn.textContent;btn.textContent='Copied';setTimeout(()=>btn.textContent=old,900)}catch{prompt('Copy this command:',btn.dataset.copy)}}));
}

const modal=document.querySelector('#searchModal'), input=document.querySelector('#searchInput'), results=document.querySelector('#searchResults');
const entries=Object.entries(PAGES).map(([k,p])=>({k,title:p.title,desc:p.sub,text:JSON.stringify(p).toLowerCase()}));
function openSearch(){modal.classList.remove('hidden');modal.setAttribute('aria-hidden','false');input.value='';input.focus();drawResults();}
function closeSearch(){modal.classList.add('hidden');modal.setAttribute('aria-hidden','true');}
function drawResults(){const q=input.value.toLowerCase().trim();const found=entries.filter(x=>!q||x.title.toLowerCase().includes(q)||x.desc.toLowerCase().includes(q)||x.text.includes(q)).slice(0,16);results.innerHTML=found.length?found.map(x=>`<a class="result" href="#${x.k}"><strong>${esc(x.title)}</strong><small>${esc(x.desc)}</small></a>`).join(''):'<p style="color:#96a1aa">No matching pages.</p>';}
document.querySelector('#searchBtn').addEventListener('click',openSearch);document.querySelector('#closeSearch').addEventListener('click',closeSearch);modal.addEventListener('click',e=>{if(e.target===modal)closeSearch()});input.addEventListener('input',drawResults);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeSearch();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch()}});
const menuBtn=document.querySelector('#menuBtn');menuBtn.addEventListener('click',()=>{const sb=document.querySelector('#sidebar');const open=sb.classList.toggle('mobile-open');menuBtn.setAttribute('aria-expanded',String(open));});
document.querySelector('#sidebar').addEventListener('click',()=>{if(window.innerWidth<=850)document.querySelector('#sidebar').classList.remove('mobile-open')});
window.addEventListener('hashchange',route);route();
